name: publish on github

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: "@Daniel1442"
      - run: yarn install
      - run: yarn run build
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: 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